/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8eb",
        "inverse-primary": "#a0c9ff",
        "on-primary-container": "#e2ecff",
        "secondary-fixed": "#7df6ea",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f7",
        "tertiary-fixed-dim": "#ffb59d",
        "primary-fixed": "#d2e4ff",
        "on-secondary-container": "#00716a",
        "surface-container-highest": "#e0e3e6",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-dim": "#d8dadd",
        "on-secondary-fixed": "#00201d",
        "on-tertiary-fixed": "#390b00",
        "surface": "#f7f9fc",
        "tertiary-fixed": "#ffdbd0",
        "surface-bright": "#f7f9fc",
        "secondary": "#006a63",
        "outline": "#717782",
        "surface-container": "#eceef1",
        "tertiary": "#8e3718",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#7e2b0d",
        "tertiary-container": "#ad4e2d",
        "background": "#f7f9fc",
        "primary": "#005492",
        "on-secondary-fixed-variant": "#00504b",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffe7e0",
        "inverse-on-surface": "#eff1f4",
        "primary-fixed-dim": "#a0c9ff",
        "secondary-fixed-dim": "#5ed9ce",
        "on-background": "#191c1e",
        "surface-tint": "#0061a6",
        "outline-variant": "#c1c7d2",
        "primary-container": "#1a6db5",
        "secondary-container": "#7df6ea",
        "on-surface-variant": "#414751",
        "on-primary-fixed-variant": "#00497f",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001c37",
        "surface-variant": "#e0e3e6",
        "error-container": "#ffdad6",
        "hero-orange": "#F4845F"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "80px",
        "gutter": "24px",
        "lg": "48px",
        "xs": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "base": "4px",
        "md": "24px",
        "sm": "16px"
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "caption": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
      fontSize: {
        "label-bold": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-hero": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-hero-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
